spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beauty_ssm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
asyn:
  #core核心必填项
  core:
    #所在环境 会保证到表中 这样就可以解决预发环境的命令只会在预发环境上执行 做到不同环境之间哪怕用的数据库一样 也可以隔离
    env: test
    #定时任务名称 重点：需要不同工程不一样 推荐用应用名称来命名 如果多个项目定义的相同 定时任务会有问题
    jobName: test-boot
    #分表数量 正式环境一定要填写 设置需要是2的倍数如 4 8 16 32 64 因为分表位计算是通过biz_id 然后和hashmap相同的计算下标的方式 & hash
    #4代表分了4张异步命令表
    #也代表有4个线程同时捞取4张异步命令表的数据进行执行 测试环境可以不填写
    #默认一张异步命令表 后台只会有一个线程捞取数据
    tableNum: 4
    #zookeeper地址
    zookeeperUrl: 127.0.0.1:2181
    #重试执行频率 5s,10s,1m,1h 频率建议不要小于1秒
    #代表第一次重试5秒以后执行 第二次10秒以后执行 第三次1分钟以后执行 第四次1小时以后执行 之后都是间隔1小时执行
    #执行频率 5s,10s,20s
    #代表第一次重试5秒以后执行 第二次10秒以后执行 第三次20秒以后执行
    #这个参数如果想不同异步命令频率不一样 可以在异步命令执行器也有参数可以设置
    executerFrequencys: 4s,5s,6s
  #以下非必填
  #执行线程池配置
  pool:
    #最小线程池 默认10
    corePoolSize: 20
    #最大线程数 默认150
    maxPoolSize: 200
    #缓存队列长度 默认300
    queueCapacity: 300
  #调度中心调度执行相关配置
  executerjob:
    #从数据库捞取未执行的异步命令多久捞取一次 默认是1秒捞取一次  0/2 * * * * ?代表2秒捞取一次
    cron: 0/2 * * * * ?
    #异步命令是否要先进后出 默认先进先出 true代表后进先出 注意这个只针对一张表的情况
    desc: true
    #一次从一张表中捞取命令数量 默认20条数据 10代表捞取10条数据
    limit: 20
    #重试次数 默认重试12次 20代表重试20次
    retryNum: 20
  #备份定时任务相关配置
  backupjob:
    #是否开启自动备份异步命令表的功能 开启需要在数据库中创建异步命令历史表 表的数量和异步命令表相同
    #默认每天凌晨2点钟开启定时任务把一个月以前的数据从异步命令表拷贝到异步命令历史表中 把异步命令表中备份成功的数据删除
    #最多每天同步每张表10w条数据 这样定时清理数据可以保证异步命令表的查询效率高
    #可以修改默认配置
    backup: true
    #配置什么时候执行定时任务 默认每天凌晨2点
    backupCron: 0/3 * * * * ?
    #配置备份多久以前的数据 20代表把20天以前的异步命令表数据都清理 备份到异步命令历史表中
    beforeDate: 3
    #配置备份任务一次最多每张表处理多少条数据 默认是10w条数据 10代表处理1w条数据
    maxNo: 20
  restjob:
    #重置状态任务执行频率 默认每隔60秒执行一次
    restCron: 0/30 * * * * ?


